// <auto-generated />
using System;
using ClinicManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicManagement.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20251115180314_Auth migration")]
    partial class Authmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicManagement.Models.Auth.PromotionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("ProcessedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("RequestedRoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByAdminId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedRoleId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("PromotionRequests");
                });

            modelBuilder.Entity("ClinicManagement.Models.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAcceptPromotions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanAskPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanDownloadCsv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanExecuteRawQueries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanManageUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanViewPromotionsList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CanViewUserData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanAcceptPromotions = false,
                            CanAskPromotion = false,
                            CanCreate = false,
                            CanDelete = false,
                            CanDownloadCsv = false,
                            CanExecuteRawQueries = false,
                            CanManageUsers = false,
                            CanRead = true,
                            CanUpdate = false,
                            CanViewPromotionsList = false,
                            CanViewUserData = false,
                            Name = "Guest",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CanAcceptPromotions = false,
                            CanAskPromotion = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanDownloadCsv = false,
                            CanExecuteRawQueries = false,
                            CanManageUsers = false,
                            CanRead = true,
                            CanUpdate = true,
                            CanViewPromotionsList = false,
                            CanViewUserData = false,
                            Name = "Authorized",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CanAcceptPromotions = false,
                            CanAskPromotion = true,
                            CanCreate = true,
                            CanDelete = true,
                            CanDownloadCsv = true,
                            CanExecuteRawQueries = true,
                            CanManageUsers = false,
                            CanRead = true,
                            CanUpdate = true,
                            CanViewPromotionsList = false,
                            CanViewUserData = false,
                            Name = "Operator",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            CanAcceptPromotions = true,
                            CanAskPromotion = false,
                            CanCreate = true,
                            CanDelete = true,
                            CanDownloadCsv = true,
                            CanExecuteRawQueries = true,
                            CanManageUsers = true,
                            CanRead = true,
                            CanUpdate = true,
                            CanViewPromotionsList = true,
                            CanViewUserData = true,
                            Name = "Admin",
                            Type = 3
                        });
                });

            modelBuilder.Entity("ClinicManagement.Models.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClinicManagement.Models.Facilities.Cabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Building")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Cabinets");
                });

            modelBuilder.Entity("ClinicManagement.Models.Facilities.CabinetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CabinetTypes");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Sickness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sicknesses");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.SicknessProcedure", b =>
                {
                    b.Property<int>("SicknessId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer");

                    b.HasKey("SicknessId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("SicknessProcedures");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.SicknessSymptom", b =>
                {
                    b.Property<int>("SicknessId")
                        .HasColumnType("integer");

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.HasKey("SicknessId", "SymptomId");

                    b.HasIndex("SymptomId");

                    b.ToTable("SicknessSymptoms");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.SicknessTreatment", b =>
                {
                    b.Property<int>("SicknessId")
                        .HasColumnType("integer");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("integer");

                    b.HasKey("SicknessId", "TreatmentId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("SicknessTreatments");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.DistrictDoctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId");

                    b.ToTable("DistrictDoctors");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("integer");

                    b.Property<bool>("DidItHappen")
                        .HasColumnType("boolean");

                    b.Property<int>("DoctorProcedureId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamptz");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("DoctorProcedureId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.DoctorOnCallStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("DoctorOnCallStatuses");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.DoctorProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("DoctorProcedures");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.HomeCallLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamptz");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DoctorId");

                    b.ToTable("HomeCallLogs");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ClinicManagement.Models.Auth.PromotionRequest", b =>
                {
                    b.HasOne("ClinicManagement.Models.Auth.User", "ProcessedByAdmin")
                        .WithMany()
                        .HasForeignKey("ProcessedByAdminId");

                    b.HasOne("ClinicManagement.Models.Auth.Role", "RequestedRole")
                        .WithMany()
                        .HasForeignKey("RequestedRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Auth.User", null)
                        .WithMany("PromotionRequests")
                        .HasForeignKey("UserId1");

                    b.Navigation("ProcessedByAdmin");

                    b.Navigation("RequestedRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicManagement.Models.Auth.User", b =>
                {
                    b.HasOne("ClinicManagement.Models.Auth.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClinicManagement.Models.Facilities.Cabinet", b =>
                {
                    b.HasOne("ClinicManagement.Models.Facilities.CabinetType", "Type")
                        .WithMany("Cabinets")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Diagnosis", b =>
                {
                    b.HasOne("ClinicManagement.Models.Info.Appointment", "Appointment")
                        .WithOne("Diagnosis")
                        .HasForeignKey("ClinicManagement.Models.Health.Diagnosis", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.SicknessProcedure", b =>
                {
                    b.HasOne("ClinicManagement.Models.Health.Procedure", "Procedure")
                        .WithMany("SicknessProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Health.Sickness", "Sickness")
                        .WithMany("SicknessProcedures")
                        .HasForeignKey("SicknessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procedure");

                    b.Navigation("Sickness");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.SicknessSymptom", b =>
                {
                    b.HasOne("ClinicManagement.Models.Health.Sickness", "Sickness")
                        .WithMany("SicknessSymptoms")
                        .HasForeignKey("SicknessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Health.Symptom", "Symptom")
                        .WithMany("SicknessSymptoms")
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sickness");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.SicknessTreatment", b =>
                {
                    b.HasOne("ClinicManagement.Models.Health.Sickness", "Sickness")
                        .WithMany("SicknessTreatment")
                        .HasForeignKey("SicknessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Health.Treatment", "Treatment")
                        .WithMany("SicknessTreatment")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sickness");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.DistrictDoctor", b =>
                {
                    b.HasOne("ClinicManagement.Models.Humans.Doctor", "Doctor")
                        .WithOne("DistrictDoctor")
                        .HasForeignKey("ClinicManagement.Models.Humans.DistrictDoctor", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Doctor", b =>
                {
                    b.HasOne("ClinicManagement.Models.Humans.Person", "Person")
                        .WithOne("Doctor")
                        .HasForeignKey("ClinicManagement.Models.Humans.Doctor", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Humans.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Patient", b =>
                {
                    b.HasOne("ClinicManagement.Models.Info.Address", "Address")
                        .WithMany("Patients")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Humans.Person", "Person")
                        .WithOne("Patient")
                        .HasForeignKey("ClinicManagement.Models.Humans.Patient", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.Appointment", b =>
                {
                    b.HasOne("ClinicManagement.Models.Facilities.Cabinet", "Cabinet")
                        .WithMany("Appointments")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Info.DoctorProcedure", "DoctorProcedure")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Humans.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("DoctorProcedure");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.DoctorOnCallStatus", b =>
                {
                    b.HasOne("ClinicManagement.Models.Info.Address", "Address")
                        .WithMany("DoctorOnCallStatuses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Humans.Doctor", "Doctor")
                        .WithOne("OnCallStatus")
                        .HasForeignKey("ClinicManagement.Models.Info.DoctorOnCallStatus", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.DoctorProcedure", b =>
                {
                    b.HasOne("ClinicManagement.Models.Humans.Doctor", "Doctor")
                        .WithMany("DoctorProcedures")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Health.Procedure", "Procedure")
                        .WithMany("DoctorProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.HomeCallLog", b =>
                {
                    b.HasOne("ClinicManagement.Models.Info.Address", "Address")
                        .WithMany("HomeCallLogs")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Humans.Doctor", "Doctor")
                        .WithMany("HomeCallLogs")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.Schedule", b =>
                {
                    b.HasOne("ClinicManagement.Models.Facilities.Cabinet", "Cabinet")
                        .WithMany("Schedules")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagement.Models.Humans.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagement.Models.Auth.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClinicManagement.Models.Auth.User", b =>
                {
                    b.Navigation("PromotionRequests");
                });

            modelBuilder.Entity("ClinicManagement.Models.Facilities.Cabinet", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ClinicManagement.Models.Facilities.CabinetType", b =>
                {
                    b.Navigation("Cabinets");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Procedure", b =>
                {
                    b.Navigation("DoctorProcedures");

                    b.Navigation("SicknessProcedures");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Sickness", b =>
                {
                    b.Navigation("SicknessProcedures");

                    b.Navigation("SicknessSymptoms");

                    b.Navigation("SicknessTreatment");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Symptom", b =>
                {
                    b.Navigation("SicknessSymptoms");
                });

            modelBuilder.Entity("ClinicManagement.Models.Health.Treatment", b =>
                {
                    b.Navigation("SicknessTreatment");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Doctor", b =>
                {
                    b.Navigation("DistrictDoctor");

                    b.Navigation("DoctorProcedures");

                    b.Navigation("HomeCallLogs");

                    b.Navigation("OnCallStatus");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Person", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicManagement.Models.Humans.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.Address", b =>
                {
                    b.Navigation("DoctorOnCallStatuses");

                    b.Navigation("HomeCallLogs");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.Appointment", b =>
                {
                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("ClinicManagement.Models.Info.DoctorProcedure", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
